apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yusi-prod

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: yusi.aseubel.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: yusi.aseubel.com
  target:
    kind: Ingress
    name: yusi-ingress
images:
- name: yusi-backend
  newName: ghcr.io/aseubel/yusi/yusi-backend
  newTag: df8242d2492800fef214e0f6ec16c2773ec81e54
- name: yusi-frontend
  newName: ghcr.io/aseubel/yusi/yusi-frontend
  newTag: df8242d2492800fef214e0f6ec16c2773ec81e54
- name: yusi-mcp
  newName: ghcr.io/aseubel/yusi/yusi-mcp
  newTag: df8242d2492800fef214e0f6ec16c2773ec81e54
